server:
  port: 7070

spring:
  profiles:
    active: dev  # 기본적으로 dev 환경에서 실행되도록 설정
    include: secret
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operationsSorter: method
    persistAuthorization: true  # 페이지 새로고침 시에도 인증 유지
    display-request-duration: true
    csrf:
      enabled: false  # CSRF 보안 해제
  paths-to-match: /**

spring:
  servlet:
    multipart:
      max-file-size: 100MB  # multipart 설정 적용
      max-request-size: 500MB
  jackson:
    time-zone: Asia/Seoul  # JSON 타임존 설정
