spring:
  datasource:
    hikari:
      maximum-pool-size: 10      # 커넥션 풀 사이즈
      minimum-idle: 5            # 최소 유휴 커넥션
      idle-timeout: 30000        # 유휴 커넥션 타임아웃
      pool-name: HikariCP
      max-lifetime: 1800000      # 커넥션 최대 수명

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true        # SQL 쿼리 포맷팅
        use_sql_comments: true  # 쿼리 주석 추가
        jdbc:
          time_zone: UTC        # 타임존 설정
