spring:
  profiles:
    active: local  # 기본적으로 로컬 환경을 활성화
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      operationsSorter: method
      tagsSorter: alpha
      persistAuthorization: true  # 페이지 새로고침 시에도 인증 유지

  jackson:
    time-zone: Asia/Seoul       # JSON 타임존 설정

server:
  port: 80

# Swagger 보안 설정 (추가)
springdoc:
  swagger-ui:
    csrf:
      enabled: false
  paths-to-match: /**
