spring:
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      operationsSorter: method
      tagsSorter: alpha
      persistAuthorization: true  # 페이지 새로고침 시에도 인증 유지
  datasource:
    url: jdbc:mariadb://localhost:3306/sideproject
    username: root
    password:  # 비밀번호 입력 또는 환경변수 사용
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10      # 커넥션 풀 사이즈
      minimum-idle: 5            # 최소 유휴 커넥션
      idle-timeout: 30000        # 유휴 커넥션 타임아웃
      pool-name: HikariCP
      max-lifetime: 1800000      # 커넥션 최대 수명
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true        # SQL 쿼리 포맷팅
        use_sql_comments: true  # 쿼리 주석 추가
        jdbc:
          time_zone: UTC        # 타임존 설정
  jackson:
    time-zone: Asia/Seoul       # JSON 타임존 설정

server:
  port: 80

# Swagger 보안 설정 (추가)
springdoc:
  swagger-ui:
    csrf:
      enabled: false
  paths-to-match: /**
