spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # 테스트 실행 시 매번 DB 초기화
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always  # 테스트 실행 시 DB가 없으면 자동 생성
