server:
  port: 7070

spring:
  spring:
    config:
      import: optional:.env
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본적으로 dev 환경에서 실행되도록 설정
  #    include: secret
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB  # multipart 설정 적용
      max-request-size: 500MB
  jackson:
    time-zone: Asia/Seoul  # JSON 타임존 설정

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operationsSorter: method
    persistAuthorization: true  # 페이지 새로고침 시에도 인증 유지
    display-request-duration: true
    csrf:
      enabled: false  # CSRF 보안 해제
  paths-to-match: /**